SELECT IdCategoria, Descripcion, Estado FROM CATEGORIA

SELECT * FROM CATEGORIA

INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('LACTEOS',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('EMBUTIDOS',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('PIROTECNIA',0)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('BEBIDAS',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('BEBIDAS ALCOHOLICAS',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('DESPENSA',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('ARTICULOS DE LIMPIEZA',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('HIGIENE PERSONAL',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('HELADOS',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('GOLOSINAS',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('ALFAJORES',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('KIOSCO',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('TABAQUERIA',1)
INSERT INTO CATEGORIA (Descripcion, Estado) VALUES ('ENLATADOS',1)